spring:
  application:
    name: qigetech-mark
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELETE 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      connection-properties: druid.stat.mergeSql = true; druild.stat.slowSqlMillis=500
      use-global-data-source-stat: true
      url: jdbc:mysql://localhost:3306/qige_corpus?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&autoReconnectForPools=true
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        login-username: admin
        login-password: admin
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 1234
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234Redis
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
    lettuce:
      shutdown-timeout: 600

# Mybatis-plus????
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.xiaohan.bootdemo.entity
  configuration:
    map-underscore-to-camel-case: true  #??????????????
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      table-underline: true

server:
  port: 8087
  max-http-header-size: 10KB
