# 项目服务器配置（默认是下面的，不写也行）
server:
  port: 8080
  context-path: /


#==========logback start===================
#logging:
#    level:
#        com.lxj.controller.common.Test1Controller: 'off'

#==========logback end===================

#==========mysql redis druid等start===================
spring:
  application:
    name: store
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&autoReconnectForPools=true
    username: root
    password: 1234
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    tomcat:
        max-active: 150
        max-idle: 50
        min-idle: 10
        initial-size: 10
        time-between-eviction-runs-millis: 30000
        min-evictable-idle-time-millis: 60000

  redis: # redis配置
      host: 127.0.0.1
      port: 6379
      timeout: 20000
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1



#访问：127.0.0.1:8080/druid/login.html
druid:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 1234
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

#========== end===================

#========== mybatis start===================
mybatis:
    # 自动扫描
    type-aliases-package: com.lxj.pojo
    configuration:
        # 打开延迟加载 的开关
        lazy-loading-enabled: true
        # 将积极加载改为消极加载即按需要加载
        aggressive-lazy-loading: false
        # 开启二级缓存
        cache-enabled: true
        # 支持驼峰命名法
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers: com.lxj.util.MyMapper
    not-empty: false
    identity: MYSQL


pagehelper:
  helperDialect: mysql
  # 数据合理化：true时在pageNum<1会查询第一页，如果pageNum>pages会查询最后一页,false:返回null
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#========== mybatis end===================




